//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntryTestManagement.Models
{
    using System.ComponentModel.DataAnnotations;

    public partial class Complaint
    {
        public int Id { get; set; }
        public string Date { get; set; }
        public string Status { get; set; }
        public string UserEmail { get; set; }
        [Required(ErrorMessage = "Complaint Subject is Required")]
        public string Subject { get; set; }
        [Required(ErrorMessage = "Description is Required")]
        public string Description { get; set; }
    }
}
