//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntryTestManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Group
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Name is Required")]
        public string Name { get; set; }
        public string IsFull { get; set; }
        [Required(ErrorMessage = "Time is Required")]
        public Nullable<System.TimeSpan> Time { get; set; }
        [Required(ErrorMessage = "Date is Required")]
        public Nullable<System.DateTime> Date { get; set; }
    }
}
