//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntryTestManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RollNumberSlip
    {
        public RollNumberSlip()
        {
        }

        public int Id { get; set; }
        public Nullable<decimal> RollNo { get; set; }
        public Nullable<decimal> FormID { get; set; }
        public string HallName { get; set; }
        public Nullable<decimal> SeatNo { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public string UserEmail { get; set; }
    }
}
